spring.application.name=ipv6

#server.address=fe80::d533:515d:ae9:aed6
server.address=fe80::e0e7:a130:e63:3678
# Bind to all available IPv6 addresses
server.port=8089



#server.ssl.key-store=classpath:server.jks
#server.ssl.key-store-password=hassan123
#server.ssl.key-store-type=JKS
#server.ssl.key-alias=hassan123